create table dept (deptno int, deptname varchar(20), location varchar(20));
insert into dept values(11,'Sales','Mumbai');
insert into dept values(21,'Sales','Pune');
insert into dept values(15,'Marketing','Pune');
insert into dept values(12,'Marketing','Mumbai');
select * from test.dept;
select distinct location from dept;
select * from test.employee;
desc employee;
alter table employee add primary key(empid);
alter table employee add primary key(empid);
desc employee;
alter table employee add primary key(empid);
drop table test.employee;
create table emp (empno int, empname varchar(20), salary int, address varchar(20));
insert into emp values(1,'sudha',30000,'pune');
insert into emp values(2,'mudha',40000,'mumbai');
insert into emp values(1,'megha',50000,'pune');
insert into emp values(1,'ashwini',60000,'mumbai');
insert into emp values(1,'ashshi',70000,'nashik');
select * from test.emp;
alter table emp add primary key(empno);
desc emp;
alter table emp add primary key(empno);
alter table test.emp add primary key(empno);
select * from test.emp;
drop table test.emp;
create table emp (empno int, empname varchar(20), salary int, address varchar(20));
insert into emp values(1,'sudha',30000,'pune');
insert into emp values(2,'mudha',40000,'mumbai');
insert into emp values(3,'megha',50000,'pune');
insert into emp values(4,'ashwini',60000,'mumbai');
insert into emp values(5,'ashshi',70000,'nashik');
select * from test.emp;
alter table emp add primary key(empno);
alter table dept add primary key(deptno);
select * from test.dept;
delete from  dept  where deptno = 11;
drop table test.dept;
create table dept (deptno int, deptname varchar(20), location varchar(20));
insert into dept values(11,'Sales','Mumbai');
insert into dept values(21,'Sales','Pune');
insert into dept values(15,'Marketing','Pune');
insert into dept values(12,'Marketing','Mumbai');
select * from test.dept;
desc dept;
alter table emp add column deptno int;
desc dept;
desc emp;
desc emp;
alter table emp add foreign key(deptno) references dept(deptno);
desc emp;
select * from emp;
update emp set deptno = 12 where deptno is null;

desc emp;
select * from emp;
update emp set deptno=11 where empno=4;
select * from emp;
select * from emp limit 3;
select * from emo limit 1;
select * from emp limit 1;
select * from emp order by salary desc limit 3;
select * from emp order by salary desc limit 1;
select * from emp order by rand() limit 1;
select * from emp order by rand() limit 1;
select empno as "Employee Number", empname as "Employee Name",salary,address from emp;
select * from emp where empname in(sudha,ashwini);
select * from emp;
select * from emp where empname in(sudha,ashwini);
select * from emp where empname in('sudha','ashwini');
select * from emp where salary in(30000,50000);
select * from emp where salary between 10000 and 50000;
select * from emp where deptno=11 and deptno=12;
select * from emp where deptno=11 or deptno=12;
select * from emp where deptno=12 and address='pune';